### ISSUE TITLE
Random parameters are sorted alphabetically

### ISSUE THREAD

**Issue by mhovd** [LAPKB/PMcore#44]
Possible solutions:

- Force Pmetrics (and users) to declare parameters in alphabetical order
- Migrate away from `config` to something that allows us to preserve order
- Manually read using TOML, then add `ENV` with `config`

**Comment by mnneely** [comment]
I don’t like solution 1 as much, because it is desirable often, especially with complex models, to group associated parameters, and they may not be alphabetical. Could we not assign the rank based on the location in the original definition and then sort by rank if alphabetical sorting is ever imposed by various functions?

**Comment by mhovd** [comment]
I fully agree @mnneely. The problem comes from a bug in the crate (library) we use to parse the configuration file. We are working on a fix!

**Comment by mhovd** [comment]
Solved by @Siel
